### ISSUE TITLE
Project Ideas

### ISSUE THREAD

**Issue by brotherson67** [brotherson67/glowing-spork#1]
Below are some Ideas of what we may create

**Comment by brotherson67** [comment]
A combination of our previous applications. A weather-telling, route-creating, friend-making, hiking, climbing, granola app which will inspire and help people to take part in outdoor activities.

**Comment by brotherson67** [comment]
habit/mindfulness app

**Comment by brotherson67** [comment]
learning to code site

**Comment by Plaindemon** [comment]
We could change the climbing friends app to a skiing find friends app and we could see if we could get it to link up and get data from strava api docs or something?

**Comment by brotherson67** [comment]
We have decided on a social media app where people can find local activities that interest them and share their accomplishements
