### ISSUE TITLE
link Strava APi to the back end

### ISSUE THREAD

**Issue by Plaindemon** [brotherson67/glowing-spork#16]

**Comment by brotherson67** [comment]
currently, when one visits the profile page and attempts to log in via strava they are taken to the same authentication for the same user, our goal right now is to find how to differentiate and make this authentication dynamic.

**Comment by brotherson67** [comment]
I do have reservations about this, it seems to me that the different secrets and tokens only pertain to a single user which would make using the strava api to get the activities for every user unrealistic because we would need to know these tokens and secrets for each one.
